export const API_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
}

export const API_ROUTES = {
  LINKS: {
    BASE: '/links',
    UPDATE: '/links/:id',
  },
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH_TOKEN: '/auth/refresh-token',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: '/auth/resend-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    BASE: '/users',
    SEARCH: '/users/search',
    GET_ALL: '/users',
    GET_BY_ID: '/users/:id',
    GET_BY_ROLE: '/users/role/:role',
    UPDATE_PROFILE: '/users/profile',
    UPDATE_AVATAR: '/users/profile/avatar',
    CHANGE_PASSWORD: '/users/change-password',
    DELETE: '/users/:id',
    SOFT_DELETE: '/users/:id/soft-delete',
    GET_PROFILE: '/users/profile',
    ADD_MONEY: '/users/:id/add-money',
  },
  TICKETS: {
    BASE: '/tickets',
    GET_ALL: '/tickets',
    GET_BY_ID: '/tickets/:id',
    CREATE: '/tickets',
    UPDATE: '/tickets/:id',
    DELETE: '/tickets/:id',
    MY_TICKETS: '/tickets/my-tickets',
  },
  LICENSES: {
    BASE: '/api-management/licenses',
    UPGRADE: '/api-management/licenses/upgrade',
    VALIDATE: '/api-management/licenses/validate',
    ACTIVATE: '/api-management/licenses/activate',
  },
  LICENSE_KEYS: {
    BASE: '/license-keys',
    GET_ALL: '/license-keys',
    GET_STATS: '/license-keys/stats',
    GET_MY_KEYS: '/license-keys/my-keys',
    SYNC: '/license-keys/sync',
    PURCHASE: '/license-keys/purchase',
    DELETE: '/license-keys/:id',
    // Old endpoints (for external API)
    GET_BY_ID: '/api-management/license-keys/:id',
    CREATE: '/api-management/license-keys',
    UPDATE: '/api-management/license-keys/:id',
    DELETE_EXTERNAL: '/api-management/license-keys/:id',
    GENERATE: '/api-management/license-keys/generate/batch',
  },
  WALLET: {
    BASE: '/wallet',
    BALANCE: '/wallet/balance',
    CREATE_TOPUP: '/wallet/topup',
    TOPUPS: '/wallet/topups',
    TOPUP_DETAIL: '/wallet/topups/:topupCode',
    VNPAY_RETURN: '/wallet/vnpay/return',
  },
}
