export const API_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
}

export const API_ROUTES = {
  LINKS: {
    BASE: '/links',
    UPDATE: '/links/:id',
  },
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH_TOKEN: '/auth/refresh-token',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: '/auth/resend-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    BASE: '/users',
    SEARCH: '/users/search',
    GET_ALL: '/users',
    GET_BY_ID: '/users/:id',
    GET_BY_ROLE: '/users/role/:role',
    UPDATE_PROFILE: '/users/profile',
    UPDATE_AVATAR: '/users/profile/avatar',
    CHANGE_PASSWORD: '/users/change-password',
    DELETE: '/users/:id',
    SOFT_DELETE: '/users/:id/soft-delete',
    GET_PROFILE: '/users/profile',
  },
  TICKETS: {
    BASE: '/tickets',
    GET_ALL: '/tickets',
    GET_BY_ID: '/tickets/:id',
    CREATE: '/tickets',
    UPDATE: '/tickets/:id',
    DELETE: '/tickets/:id',
    MY_TICKETS: '/tickets/my-tickets',
  },
  LICENSES: {
    BASE: '/api-management/licenses',
    UPGRADE: '/api-management/licenses/upgrade',
    VALIDATE: '/api-management/licenses/validate',
    ACTIVATE: '/api-management/licenses/activate',
  },
  LICENSE_KEYS: {
    BASE: '/api-management/license-keys',
    GET_ALL: '/api-management/license-keys',
    GET_BY_ID: '/api-management/license-keys/:id',
    CREATE: '/api-management/license-keys',
    UPDATE: '/api-management/license-keys/:id',
    DELETE: '/api-management/license-keys/:id',
    GENERATE: '/api-management/license-keys/generate/batch',
  },
}
